- docker-compose/docker-compose.yml
> 添加mongo-gui，在用户管理面板实现之前，实现对用户的暂时管理

- service/package.json
- service/pnpm-lock.yaml
- service/src/index.ts
- service/src/storage/model.ts
- service/src/storage/mongo.ts
> 需要升级依赖 chatgpt 到 [5.2.0+](https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v5.2.0)
> 这在主 Repo 遇到了[问题](https://github.com/Chanzhaoyu/chatgpt-web/commit/abc4c3ad223b8f2498ca3e01aaafeb0339ef80f8)，不过我试下来没什么发现
单独建表而不是更新在原来的 ChatInfo 表，是因为考虑到一个问题可以多次生成回答，如果都记录下来在一个 ChatInfo 中必然会有多层，对统计不友好。而单独建一个统计表也方便之后如果有需要统计每个用户的使用量，各个表的 ID 都在，应该可以链回原来表的，信息不冗余也不缺失
> 记录每个请求的 Token 消耗(预估)

- service/src/chatgpt/index.ts
- service/src/storage/mongo.ts
重启服务后上下文在提问中得以保存
同时关掉 api 依赖库中的缓存以减少长时间使用后的内存占用
---
可能带来的问题是上下文条数很多时多次读取 MongoDB 数据库，会加大数据库压力和增大延迟，可以做的优化是做一层小缓存
---
只试过 API 走 GPT 3.5，accessToken 方式需要测试
> 聊天历史由 MongoDB 中获取

- service/src/storage/mongo.ts
如果MongoDB URL有数据名，使用MongoDB URL里的数据库名称，否则使用默认数据库名称
> 使用MongoDB URL里的数据库名称

- src/views/chat/components/Message/index.vue
fix: https://github.com/Kerwin1202/chatgpt-web/issues/252
import 少了NButton，导致console warnnig
可能因为有import NButtonGroup，vscode并未报错
> fix: Failed to resolve component NButton

- service/src/chatgpt/index.ts
- service/src/index.ts
- src/api/index.ts
fix issue https://github.com/Kerwin1202/chatgpt-web/issues/259
另外通过添加interface处理了两个 Property does not exist on type 'unknown'.ts(2339) 的小问题，对ts不太熟悉，如果画蛇添足了请批评教育
> fix: remove unused fetchChatAPI

- service/src/utils/templates/mail.admin.template.html
- service/src/utils/templates/mail.notice.template.html
- service/src/utils/templates/mail.resetpassword.template.html
- service/src/utils/templates/mail.template.html
- src/components/common/HoverButton/Button.vue
- src/views/chat/components/Header/index.vue
- src/views/chat/index.vue
有些邮箱不支持直接点击按钮，禁用了a元素，并且无法查看href上的链接。
这样会造成使用体验中断，所以还是增加了显示URL的功能。
顺便重构了一下邮件的代码，移除了一些多余的内容。
修改后效果如下：
> feat: refactor mail template and add link address for copy

- service/src/chatgpt/index.ts
fix the max tokens for gpt-4-turbo 128K
> fix the max tokens for gpt-4-turbo 128K

- service/package.json
- service/pnpm-lock.yaml
- service/src/index.ts
- service/src/storage/mongo.ts
避免在 接口 `/room-rename` 中将 mongodb 的更新结果 `UpdateResult` 直接返回到前端
以同样的风格应用到了其他接口上 避免可能产生类似的问题
更新了 `mongodb driver` 版本 并且替换了新版本中已弃用的方法 `cursor.forEach()`
另外 从 `mongodb` 4.x 开始 已经不再需要单独在 `devDependencies`中导入 `@types/mongodb` 了
> chore: backend not response mongodb UpdateResult data

- service/src/chatgpt/index.ts
- service/src/index.ts
- service/src/storage/model.ts
- service/src/storage/mongo.ts
- src/api/index.ts
- src/components/common/Setting/General.vue
- src/locales/en-US.ts
- src/locales/ko-KR.ts
- src/locales/zh-CN.ts
- src/locales/zh-TW.ts
- src/store/modules/chat/index.ts
- src/views/chat/index.vue
- src/views/chat/layout/sider/index.vue
之前修改chat model 时会修改用户级别的模型配置。影响该用户的所有 chat room
修改为针对单个 chat room 调整 所使用的 model
同时 新增 用户默认模型选择 当用户新增会话时 使用用户设置的默认值
> feat: set user deafult model & set chat model by per chat room

- service/src/storage/mongo.ts
Closed: #230 
```
MongoDB url invalid. please ensure set valid env MONGODB_URL. Cannot read properties of undefined (reading 'startsWith')
```
当未正确设置有效的 `MONGODB_URL` 打印友好的错误消息并退出进程。
> chore: improve exit log when no set MONGODB_URL env

- service/src/index.ts
- service/src/middleware/auth.ts
ref: #418 
看起来只有可能是在
https://github.com/chatgpt-web-dev/chatgpt-web/blob/39e94f258f6333842ff298f37b5108a75344f314/service/src/index.ts#L600
这里 user 为 null 了才能返回这么个错误导致页面跳转 500
再往上看又只能是 在mongo中没有查询到这个userId的情况下才会执行到这么个路径。
但是为什么数据库会查不到就想不明白了。
ping @Kerwin1202
做个判空处理先避免页面500要求重新登录如何?
> fix: attempting to fix the req /session 500 error

- Dockerfile
Avoid using outdated local node base images.
fix: #439
> chore: fixed docker base version 20-alpine

- service/src/index.ts
- service/src/storage/model.ts
- src/components/common/Setting/General.vue
- src/components/common/Setting/Site.vue
- src/components/common/Setting/User.vue
- src/components/common/Setting/model.ts
- src/locales/en-US.ts
- src/locales/zh-CN.ts
- src/store/modules/auth/index.ts
- src/store/modules/user/helper.ts
- src/store/modules/user/index.ts
https://github.com/chatgpt-web-dev/chatgpt-web/pull/430#issuecomment-1974962186
> 管理员 也显示这个兑换，不是很合理？目前看昨天的合并有一个针对每个用户的开关，没有全局的开关。
> feat: add global config option enable user usage count limit function

- README.en.md
- README.md
- service/src/middleware/auth.ts
- service/src/middleware/rootAuth.ts
- service/src/storage/config.ts
> feat: support custom auth proxy header name

- src/components/common/Setting/Statistics.vue
之前开发这个功能的时候不知道怎么更新数据后触发图表区重绘，然后 work around 了一下把图隐藏掉再显示来触发。
这个 pr 把这个改好了
> chore: optimize statistics chart render

- service/package.json
- service/pnpm-lock.yaml
- service/src/utils/image.ts
- src/views/chat/index.vue
原代码我看写死了图片类型是png，当用户上传非png图片时由于传给模型的图片类型还是png，会直接报错。我对后端进行了修改，自动判断图片类型传给模型。同时修改了前端，限定了用户上传的图片格式只能是png jpeg webp gif四种（目前openai支持也仅支持这四种图片）
> 修复当用户上传非png图片给vision模型时报错

- service/src/index.ts
- service/src/storage/model.ts
- service/src/storage/mongo.ts
- service/src/utils/image.ts
- src/components/common/Setting/Statistics.vue
> feat: add model name in chat usage records

- service/src/index.ts
- service/src/storage/mongo.ts
- src/api/index.ts
- src/components/common/Setting/Gift.vue
- src/components/common/Setting/index.vue
- src/components/common/Setting/model.ts
- src/locales/en-US.ts
- src/locales/ko-KR.ts
- src/locales/zh-CN.ts
- src/locales/zh-TW.ts
针对 #457 尝试新增了一个上传giftcard的页面，方便使用docker的用户导入，但限于post的数据量，需要记录小于2k行，个人觉得一般也够用了，有大规模导入需求的可以用其他专门管理api使用量的app来从源头限制用量或是用mongo工具导入。
上传文件的样例：
[giftcards-sample.csv](https://github.com/chatgpt-web-dev/chatgpt-web/files/14892579/giftcards-sample.csv)
> feat: add upload gift card page

- service/package.json
- service/pnpm-lock.yaml
- service/src/storage/config.ts
- service/src/storage/model.ts
- service/src/utils/mail.ts
- src/components/common/Setting/Mail.vue
- src/components/common/Setting/model.ts
- src/locales/en-US.ts
- src/locales/zh-CN.ts
> feat: support standalone mail smtp from field 

- service/src/chatgpt/index.ts
- service/src/index.ts
> fix maximum token count

- service/src/chatgpt/index.ts
and remove some deprecated models
> update/fix maximum token count, support 'chatgpt-4o-latest'
